[package]
name = "serialPlotterButCool"
version = "0.1.0"
edition = "2021"

# Specify the Rust version
[package.metadata]
rust-version = "1.60"

[dependencies]
# For time durations
serialport = "4.0"
serde_json = "1.0"
chrono = "0.4"

# Optional: Add serde if you want to use serialization/deserialization features
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "serialPlotterButCool"
path = "main.rs"